Added placeholders in update contact form and open a ticket
glific/floweditor pull request #103
Opened 2024-04-03 09:11 UTC by akanshaaa19

2024-04-15 02:22 UTC, kurund commented
@akanshaaa19 

I am wondering if this is worth submitting to upstream?

@mdshamoon 
Thoughts?

2024-04-15 02:30 UTC, kurund requested changes

2024-04-15 02:30 UTC, kurund commented on src/components/flow/actions/sendinteractivemsg/SendInteractiveMsgForm.tsx
> +          stateToRouter(this.props.nodeSettings, this.props.assetStore, this.state)
we are changing the signature of the function, I would prefer adding new params at the end.

2024-04-15 02:30 UTC, kurund commented on src/components/flow/actions/sendinteractivemsg/helpers.tsx
> +  const renderedNode = stateToNode(settings, assetStore, result);
see previous comment.

2024-04-15 02:30 UTC, kurund commented on src/components/flow/actions/updatecontact/UpdateContactForm.tsx
> +          placeholder="Select"
this needs to be localized.

2024-04-15 02:30 UTC, kurund commented on src/components/flow/routers/ticket/TicketRouterForm.tsx
> +              placeholder="Select"
needs to localized.

2024-04-18 07:56 UTC, mdshamoon approved these changes

2024-04-18 07:56 UTC, merged