Added seprate fields for subsheet and starting cell
glific/floweditor pull request #104
Opened 2024-04-19 09:40 UTC by akanshaaa19

Target issue is https://github.com/glific/glific-frontend/issues/2743

2024-04-22 16:37 UTC, mdshamoon requested changes

2024-04-22 16:37 UTC, mdshamoon commented on src/components/flow/routers/sheet/helpers.ts
> +      starting_cell.value = callSheet.range.split('!')[1].split(':')[0];
Since there is no validation for range. This will break if you provide a text that is not in the proper format like:

**Sheet1A1**

2024-05-08 07:07 UTC, mdshamoon approved these changes
Looks good. Just test it once with an already created flow that has a google sheet range.

2024-05-09 09:07 UTC, akanshaaa19 commented
> Looks good. Just test it once with an already created flow that has a google sheet range.

yess i have tested it, with the following inputs:
- Sheet1
- Sheet1!A1
- A1:A2
- Sheet1!A1:A9

2024-05-23 16:13 UTC, merged